### ISSUE TITLE
Use `editor.tabType`

### ISSUE THREAD

**Issue by benogle** [atom/language-make#21]
Now that https://github.com/atom/atom/issues/3719 is in, we should set the `editor.tabType` scoped setting in this repo.

When this lands, we can also remove the hard coded bits from atom [here](https://github.com/atom/atom/blob/927ec7aa317ffa87d834b3af95f354194b12a01f/src/text-editor.coffee#L2377-L2379) and [here](https://github.com/atom/atom/blob/927ec7aa317ffa87d834b3af95f354194b12a01f/spec/text-editor-spec.coffee#L3727-L3738)

cc @kevinsawicki

**Comment by kevinsawicki** [comment]
:+1:

**Comment by 50Wliu** [comment]
Accidentally pushed to master instead of a PR, so re-opening.
