### ISSUE TITLE
Bad highlighting of $(shell ...)

### ISSUE THREAD

**Issue by gustavnikolaj** [atom/language-make#22]
Consider this example:

```makefile
.PHONY: default
default:
	@echo "This is the decoded MSG"
	$(eval MESSAGE=$(shell node -pe "decodeURIComponent(process.argv.pop())" "${MSG}"))
	@echo "${MESSAGE}"
```

This is a perfectly valid Makefile, which is derived from a real world Makefile in a project that I work on.

Atom fails to syntax highlight this correctly:

![selection_002](https://cloud.githubusercontent.com/assets/1371503/9489544/1a976146-4be2-11e5-822f-8d1f096b298c.png)

Notice how the last line is green, and how the last to parens in `decodeURIComponent(process.argv.pop())` is highlighted in red, as if they were the closing parens for eval and shell.

I have been looking over the files in the repository, but I couldn't find the place where the `$(shell )` etc constructs are handled.

**Comment by 50Wliu** [comment]
I can't reproduce this.  For me, my Makefile highlighting appears exactly like how Github highlights it.  Can you please paste the output of `apm list --installed` here?  Thanks.

**Comment by 50Wliu** [comment]
Never mind, I accidentally used spaces instead of tabs (I've also updated your text example to match).  Whoops.
