### ISSUE TITLE
Makefile syntax highlighting bug

### ISSUE THREAD

**Issue by philtay** [atom/language-make#27]
The following code is highlighted incorrectly:

```Makefile
define foobar
$(and $(filter-out undefined,$(origin 1)),$(1))
endef

define test
command
endef
```

TextMate (and GitHub which uses [TextMate Make bundle](https://github.com/textmate/make.tmbundle)) shows it incorrectly as well.

[Gist](https://gist.github.com/philtay/5a647f5a573d1052e7f7) and [Lightshow sample](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fatom%2Flanguage-make%2Fmaster%2Fgrammars%2Fmakefile.cson&grammar_text=&code_source=from-text&code_url=&code=define+foobar%0D%0A%24%28and+%24%28filter-out+undefined%2C%24%28origin+1%29%29%2C%24%281%29%29%0D%0Aendef%0D%0A%0D%0Adefine+test%0D%0Acommand%0D%0Aendef)

Refs: https://github.com/github/linguist/issues/2710 and https://github.com/textmate/make.tmbundle/issues/9

**Comment by 50Wliu** [comment]
How do you think it should be highlighted?

**Comment by philtay** [comment]
Like this:

```Makefile
define foobar
$(and $(filter-out undefined,$(BUG 1)),$(1))
endef

define test
command
endef
```

As you can see the problem seems to be the "origin" word.

**Comment by 50Wliu** [comment]
Thanks.
