### ISSUE TITLE
Failure to highlight function invocations

### ISSUE THREAD

**Issue by alexchandel** [atom/language-make#31]
This syntax plugin always fails to highlight function invocations on separate lines:

```make
define BUILD_EXE
build_exe_$(1):
	${CARGO} build ${CARGOFLAGS} ${PROFILE_CMD} -p $(1)
endef

EXES := foo bar baz

$(foreach util,$(EXES),$(eval $(call BUILD_EXE,$(util))))
```

Notice the bare invocation at the end. This is an extremely common pattern used to generate rules, and Atom should support it.

**Comment by 50Wliu** [comment]
@alexchandel Can you take a look at the grammar file and suggest what the last line should be scoped as?

**Comment by alexchandel** [comment]
I'm afraid I'm not sure what I'm looking at in grammars/makefile.cson ... What are rules and function expansions on the RHS of variable definitions scoped as?

It's worth noting that this block, the first eval (on the second line) is highlighted correctly:
```make
define BUILD_EXE
$(eval $(1)_EXE     = $(OUT)/$(PFX$(1)).exe)
build_exe_$(1):
    ${CARGO} build ${CARGOFLAGS} ${PROFILE_CMD} -p $(1)
endef

EXES := foo bar baz

$(foreach util,$(EXES),$(eval $(call BUILD_EXE,$(util))))
```

**Comment by 50Wliu** [comment]
Ok, so the last line should be highlighted similarly to line 2?

**Comment by alexchandel** [comment]
@50Wliu Yeah. Makefile functions can have life outside of the RHS of variables. Here the `foreach` has global scope, and is used with an `eval` to cause the text returned by the `call` to be interpreted as variable/rule definitions. Super useful hack for cross-platform, multiple-target Makefiles. It pretty much lets you avoid CMake/Automake/Scons.
