### ISSUE TITLE
Failure to highlight function invocations in RHS when preceded by variable

### ISSUE THREAD

**Issue by alexchandel** [atom/language-make#34]
It successfully highlights the RHS of this as a function invocation:

``` make
TAOLNK      = $(addprefix -l, TAO ACE)
```

but when a variable is introduced, as in:

``` make
TAOLNK      = -L$(ACE_ROOT)/lib $(addprefix -l, TAO ACE)
```

The `addprefix` and all of its arguments are now incorrectly highlighted as a variable.

**Comment by 50Wliu** [comment]
Ok, I seriously have no idea why this isn't working.  The culprit seems to be the `\G` not matching after the first variable, but I see no reason as for why.

I suspect something's happening with end matching, but I'm not sure what.

**Comment by 50Wliu** [comment]
Ok something's definitely not right with `\G` after the first match, though theoretically it should just be the same thing over again?

**Comment by alexchandel** [comment]
Interestingly, this line is highlighted correctly:

```make
TAOLNK      = $() $(addprefix -l, TAO ACE)
```

Also, variables and functions calls after a function call still highlight correctly:

```make
TAOLNK      = $(shell pwd) $(addprefix -l, TAO ACE)
```

It breaks when an unrecognized function appears in parentheses and there are no spaces in between the parentheses, i.e. when it highlights a variable. Here, the second and third lines highlight incorrectly:

```make
TAOLNK      = $(shell ) $(addprefix -l, TAO ACE)
TAOLNK      = $(shell) $(addprefix -l, TAO ACE)
TAOLNK      = $(OCFLAGS ) $(addprefix -l, TAO ACE)
```

The forward lookahead `(?=\\s*\\))` in `variable.language.makefile` couldn't be interfering right?

**Comment by 50Wliu** [comment]
This was somehow fixed...I don't know how, or when, considering there have been very minimal codebase changes since I last investigated this.  Not complaining I guess.
![image](https://cloud.githubusercontent.com/assets/2766036/21793568/6f357868-d6c0-11e6-9429-02120d7c4dd3.png)

**Comment by alexchandel** [comment]
I just tested it before and after updating from 1.11.1 to 1.14.1, and that fixed it.
