### ISSUE TITLE
@# is not recognised as comment

### ISSUE THREAD

**Issue by pierstitus** [atom/language-make#40]
Using @# to add a not displaying comment in a target is not recognised as valid comment.

For example:
foo: all
    @# comment not to be displayed
    foo bar

When a space is inserted between @# it does correctly highlight.

**Comment by 50Wliu** [comment]
I'm having trouble finding documentation on `@#` comments in Make @pierstitus.  Can you please give me a link that showcases `@#` comments?

**Comment by pierstitus** [comment]
Actually it may be bad practice, as it depends on the shell whether it's interpreted as a comment or not. See https://www.gnu.org/software/make/manual/html_node/Makefile-Contents.html

> Comments within a recipe are passed to the shell, just as with any other recipe text. The shell decides how to interpret it: whether or not this is a comment is up to the shell. 

Anyway, it seems to be fixed in the meantime (in v1.12.15)
