### ISSUE TITLE
Treat Makefile.am and *.m4 as Makefiles

### ISSUE THREAD

**Issue by dogarcar** [atom/language-make#55]
Dear all,

The "Makefile.am" programmer-defined files used by automake are not recognised as Makefiles. It would be very useful if language-make provided syntax to those files.

The macros *.m4 are also not recognised by default by atom. Maybe they could also be included here.

Thanks!

Cheers.

**Comment by Alhadis** [comment]
M4 isn't Make. It's a completely different language; one which warrants its own grammar package.
